// LOAD
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS"
export const LOAD_DATA_FAILURE = "LOAD_DATA_FAILURE"

// ADD DATA
export const ADD_DATA = "ADD_DATA"
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS"
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE"

// DELETE DATA
export const DELETE_DATA = "DELETE_DATA"
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILURE = "DELETE_DATA_FAILURE"

// SEARCH DATA
export const SEARCH_DATA = "SEARCH_DATA"
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS"
export const SEARCH_DATA_FAILURE = "SEARCH_DATA_FAILURE"

// EDIT DATA
export const EDIT_DATA = "EDIT_DATA"
export const EDIT_ON = "EDIT_ON"
export const EDIT_OFF = "EDIT_OFF"
export const EDIT_DATA_SUCCESS = "EDIT_DATA_SUCCESS"
export const EDIT_DATA_FAILURE = "EDIT_DATA_FAILURE"